// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using poptwit;
using System;

namespace poptwit.Migrations
{
    [DbContext(typeof(PopContext))]
    [Migration("20180120184630_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("poptwit.Models.TweetComparison", b =>
                {
                    b.Property<long>("TweetComparisonId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AMatchCount");

                    b.Property<string>("APhrase");

                    b.Property<long>("BMatchCount");

                    b.Property<string>("BPhrase");

                    b.Property<DateTime>("Created");

                    b.Property<TimeSpan>("DateRange");

                    b.Property<long>("UserId");

                    b.HasKey("TweetComparisonId");

                    b.HasIndex("UserId");

                    b.ToTable("Comparisons");
                });

            modelBuilder.Entity("poptwit.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UID");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("poptwit.Models.TweetComparison", b =>
                {
                    b.HasOne("poptwit.Models.User", "User")
                        .WithMany("Comparisons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
